- hosts: all
  serial: 1
  tasks:
  - name : Update all packages
    apt: name="*" state=latest update_cache=true force_apt_get=true

  - name : Remove unused dependencies
    apt: autoremove=true

  - name : Check if a reboot is required.
    ansible.builtin.stat: 
      path: /var/run/reboot-required
      get_checksum: no
      register: reboot_required_file

  - name : Reboot the server (if required).
    ansible.builtin.reboot: 
      when: reboot_required_file.stat.exists == true
