- hosts: all
  serial: 1
  tasks:
  - name : Update all packages
    apt: name="*" state=latest update_cache=true force_apt_get=true

  - name : Remove unused dependencies
    apt: autoremove=true

  - name : Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name : Reboot if required
    reboot:
    when: reboot_required_file.stat.exists == true
